# Generated by Django 3.2.6 on 2022-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='bio',
            field=models.TextField(default='comentario vacio'),
            preserve_default=False,
        ),
    ]
